<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>XYPortal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XYPortal.Domain.Shared\XYPortal.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\XYPortal.LinkBoard\src\XYPortal.LinkBoard.Application.Contracts\XYPortal.LinkBoard.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\XYPortal.RandomStringProvider\src\XYPortal.RandomStringProvider.Application.Contracts\XYPortal.RandomStringProvider.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\XYPortal.PasswordBook\src\XYPortal.PasswordBook.Application.Contracts\XYPortal.PasswordBook.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.ObjectExtending" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Account.Application.Contracts" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Identity.Application.Contracts" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application.Contracts" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application.Contracts" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application.Contracts" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application.Contracts" Version="10.6.0" />
  </ItemGroup>

</Project>
