<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>XYPortal.PasswordBook</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="10.1.0" />
    <ProjectReference Include="..\XYPortal.PasswordBook.Domain\XYPortal.PasswordBook.Domain.csproj" />
  </ItemGroup>

</Project>
