<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>XYPortal.PasswordBook</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Mapperly" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Authorization" Version="10.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <ProjectReference Include="..\XYPortal.PasswordBook.Application.Contracts\XYPortal.PasswordBook.Application.Contracts.csproj" />
    <ProjectReference Include="..\XYPortal.PasswordBook.Domain\XYPortal.PasswordBook.Domain.csproj" />
    <ProjectReference Include="..\XYPortal.PasswordBook.EntityFrameworkCore\XYPortal.PasswordBook.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\XYPortal.RandomStringProvider\src\XYPortal.RandomStringProvider.Application\XYPortal.RandomStringProvider.Application.csproj" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
  </ItemGroup>

</Project>
