<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>XYPortal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XYPortal.Domain\XYPortal.Domain.csproj" />
    <ProjectReference Include="..\XYPortal.TestBase\XYPortal.TestBase.csproj" />
  </ItemGroup>

</Project>
