<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>XYPortal.PasswordBook</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XYPortal.PasswordBook.Domain\XYPortal.PasswordBook.Domain.csproj" />
    <ProjectReference Include="..\XYPortal.PasswordBook.TestBase\XYPortal.PasswordBook.TestBase.csproj" />
  </ItemGroup>


</Project>
