<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>XYPortal.LinkBoard</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Volo.Abp.PermissionManagement.EntityFrameworkCore" Version="10.6.0" />
    <ProjectReference Include="..\..\src\XYPortal.LinkBoard.Application\XYPortal.LinkBoard.Application.csproj" />
    <ProjectReference Include="..\..\src\XYPortal.LinkBoard.EntityFrameworkCore\XYPortal.LinkBoard.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\XYPortal.LinkBoard.Domain.Tests\XYPortal.LinkBoard.Domain.Tests.csproj" />
  </ItemGroup>

</Project>
