<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>XYPortal.PasswordBook</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="10.1.0" />
    <PackageReference Include="Volo.Abp.Authorization" Version="10.1.0" />
    <ProjectReference Include="..\XYPortal.PasswordBook.Domain.Shared\XYPortal.PasswordBook.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\XYPortal.RandomStringProvider\src\XYPortal.RandomStringProvider.Application.Contracts\XYPortal.RandomStringProvider.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
