<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <IsPackable>true</IsPackable>
    <OutputType>Library</OutputType>
    <RootNamespace>XYPortal.RandomStringProvider.Web</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="jQuery" Version="3.7.1" />
    <PackageReference Include="Volo.Abp.Mapperly" Version="10.1.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared" Version="10.1.0"/>
    <PackageReference Include="Volo.Abp.Localization" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XYPortal.RandomStringProvider.Application.Contracts\XYPortal.RandomStringProvider.Application.Contracts.csproj" />
    <ProjectReference Include="..\XYPortal.RandomStringProvider.Domain.Shared\XYPortal.RandomStringProvider.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Pages\**\*.cshtml" />
    <EmbeddedResource Include="Pages\**\*.css" />
    <EmbeddedResource Include="Pages\**\*.js" />
    <EmbeddedResource Include="Components\**\*.cs" />
    <EmbeddedResource Include="Components\**\*.cshtml" />
    <EmbeddedResource Include="Components\**\*.js" />
    <EmbeddedResource Include="Components\**\*.css" />
    <EmbeddedResource Include="Views\**\*.cshtml" />
    <EmbeddedResource Include="wwwroot\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\RandomStringProvider\Index.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\_ViewImports.cshtml" />
  </ItemGroup>

</Project>
