<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>XYPortal.EvGRPC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="10.6.0" />
    <ProjectReference Include="..\XYPortal.EvGRPC.Domain\XYPortal.EvGRPC.Domain.csproj" />
  </ItemGroup>

</Project>
